version: '3'
services:
  app:
    image: ldynia/ntc:1.0
    build: .
    restart: always
    container_name: ntc
    volumes:
      - ./app:/app
      - ./test:/app/test
      - ./data:/app/data
    command: sleep 36000
